apiVersion: v1
kind: Namespace
metadata:
  name: api-notes
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-notes-config
  namespace: api-notes
data:
  NOTES_PATH: "/data/notes.json"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-notes
  namespace: api-notes
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 3
  selector:
    matchLabels:
      app: api-notes
  template:
    metadata:
      labels:
        app: api-notes
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: api-notes
          image: notes-api:v2.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
          env:
            - name: NOTES_PATH
              valueFrom:
                configMapKeyRef:
                  name: api-notes-config
                  key: NOTES_PATH
          volumeMounts:
            - name: notes-storage
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5001
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: notes-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: api-notes
  namespace: api-notes
spec:
  selector:
    app: api-notes
  ports:
    - name: http
      port: 80
      targetPort: 5001
  type: ClusterIP