apiVersion: v1
kind: Namespace
metadata:
  name: api-notes
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-notes-config
  namespace: api-notes
data:
  NOTES_PATH: "/tmp/notes.json"
---
# Blue Environment (current stable)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-notes-blue
  namespace: api-notes
  labels:
    app: api-notes
    version: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-notes
      version: blue
  template:
    metadata:
      labels:
        app: api-notes
        version: blue
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: api-notes
          image: notes-api:v2.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
          env:
            - name: NOTES_PATH
              valueFrom:
                configMapKeyRef:
                  name: api-notes-config
                  key: NOTES_PATH
            - name: DEPLOYMENT_ENV
              value: "blue"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5001
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 10
---
# Green Environment (new deployment)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-notes-green
  namespace: api-notes
  labels:
    app: api-notes
    version: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-notes
      version: green
  template:
    metadata:
      labels:
        app: api-notes
        version: green
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: api-notes
          image: notes-api:v3.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
          env:
            - name: NOTES_PATH
              valueFrom:
                configMapKeyRef:
                  name: api-notes-config
                  key: NOTES_PATH
            - name: DEPLOYMENT_ENV
              value: "green"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5001
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 10
---
# Main Service (points to blue initially)
apiVersion: v1
kind: Service
metadata:
  name: api-notes
  namespace: api-notes
spec:
  selector:
    app: api-notes
    version: blue  # Initially points to blue
  ports:
    - name: http
      port: 80
      targetPort: 5001
  type: ClusterIP
---
# Green Service (for testing before switching)
apiVersion: v1
kind: Service
metadata:
  name: api-notes-green
  namespace: api-notes
spec:
  selector:
    app: api-notes
    version: green
  ports:
    - name: http
      port: 80
      targetPort: 5001
  type: ClusterIP
